steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$focal-cooler-316103/aman-100944980/app:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$focal-cooler-316103/aman-100944980/app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
